.PHONY: clean All

All:
	@echo "----------Building project:[ clasesYobjetos_cpp - Debug ]----------"
	@cd "clasesYobjetos_cpp" && "$(MAKE)" -f  "clasesYobjetos_cpp.mk"
clean:
	@echo "----------Cleaning project:[ clasesYobjetos_cpp - Debug ]----------"
	@cd "clasesYobjetos_cpp" && "$(MAKE)" -f  "clasesYobjetos_cpp.mk" clean
